CREATE INDEX "document_version_file_object_idx" ON "document_version" USING btree ("file_object_id");--> statement-breakpoint
CREATE INDEX "dossier_item_category_idx" ON "dossier_item" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "dossier_item_rule_version_idx" ON "dossier_item" USING btree ("rule_version_id");--> statement-breakpoint
CREATE INDEX "rule_version_supersedes_version_idx" ON "rule_version" USING btree ("supersedes_version_id");--> statement-breakpoint
CREATE INDEX "deadline_responsible_party_idx" ON "deadline" USING btree ("responsible_party_id");--> statement-breakpoint
CREATE INDEX "deadline_professional_party_idx" ON "deadline" USING btree ("professional_party_id");--> statement-breakpoint
CREATE INDEX "deadline_rule_version_idx" ON "deadline" USING btree ("rule_version_id");--> statement-breakpoint
CREATE INDEX "deadline_proof_document_idx" ON "deadline_proof" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "matter_assignment_party_idx" ON "matter_assignment" USING btree ("party_id");--> statement-breakpoint
CREATE INDEX "matter_document_document_idx" ON "matter_document" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "matter_document_request_requested_from_party_idx" ON "matter_document_request" USING btree ("requested_from_party_id");--> statement-breakpoint
CREATE INDEX "matter_document_request_document_idx" ON "matter_document_request" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "professional_opinion_party_idx" ON "professional_opinion" USING btree ("party_id");--> statement-breakpoint
CREATE INDEX "professional_opinion_document_idx" ON "professional_opinion" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "share_package_item_version_idx" ON "share_package_item" USING btree ("version_id");--> statement-breakpoint
CREATE INDEX "condo_agenda_document_document_idx" ON "condo_agenda_document" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condo_budget_millesimal_table_idx" ON "condo_budget" USING btree ("millesimal_table_id");--> statement-breakpoint
CREATE INDEX "condo_budget_document_idx" ON "condo_budget" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condo_claim_matter_idx" ON "condo_claim" USING btree ("matter_id");--> statement-breakpoint
CREATE INDEX "condo_contract_counterparty_party_idx" ON "condo_contract" USING btree ("counterparty_party_id");--> statement-breakpoint
CREATE INDEX "condo_contract_document_idx" ON "condo_contract" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condo_document_document_idx" ON "condo_document" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condo_installment_asset_idx" ON "condo_installment" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "condo_installment_deadline_idx" ON "condo_installment" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "condo_meeting_convocation_document_idx" ON "condo_meeting" USING btree ("convocation_document_id");--> statement-breakpoint
CREATE INDEX "condo_meeting_minutes_document_idx" ON "condo_meeting" USING btree ("minutes_document_id");--> statement-breakpoint
CREATE INDEX "condo_proxy_delegate_party_idx" ON "condo_proxy" USING btree ("delegate_party_id");--> statement-breakpoint
CREATE INDEX "condo_proxy_document_idx" ON "condo_proxy" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condo_resolution_agenda_item_idx" ON "condo_resolution" USING btree ("agenda_item_id");--> statement-breakpoint
CREATE INDEX "condo_resolution_deadline_idx" ON "condo_resolution" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "condo_resolution_budget_idx" ON "condo_resolution" USING btree ("budget_id");--> statement-breakpoint
CREATE INDEX "condo_work_resolution_idx" ON "condo_work" USING btree ("resolution_id");--> statement-breakpoint
CREATE INDEX "condo_work_entry_document_idx" ON "condo_work_entry" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "condominium_administrator_party_idx" ON "condominium" USING btree ("administrator_party_id");--> statement-breakpoint
CREATE INDEX "millesimal_share_asset_idx" ON "millesimal_share" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "tax_obligation_deadline_idx" ON "tax_obligation" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "tax_obligation_tax_type_idx" ON "tax_obligation" USING btree ("tax_type_id");--> statement-breakpoint
CREATE INDEX "tax_payment_document_idx" ON "tax_payment" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "tax_return_tax_type_idx" ON "tax_return" USING btree ("tax_type_id");--> statement-breakpoint
CREATE INDEX "tax_return_asset_idx" ON "tax_return" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "tax_return_document_idx" ON "tax_return" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "tax_return_deadline_idx" ON "tax_return" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "maint_inspection_plan_deadline_idx" ON "maint_inspection_plan" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "maint_inspection_plan_supplier_party_idx" ON "maint_inspection_plan" USING btree ("supplier_party_id");--> statement-breakpoint
CREATE INDEX "maint_invoice_document_idx" ON "maint_invoice" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "maint_quote_supplier_party_idx" ON "maint_quote" USING btree ("supplier_party_id");--> statement-breakpoint
CREATE INDEX "maint_quote_document_idx" ON "maint_quote" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "maint_warranty_work_idx" ON "maint_warranty" USING btree ("work_id");--> statement-breakpoint
CREATE INDEX "maint_warranty_supplier_party_idx" ON "maint_warranty" USING btree ("supplier_party_id");--> statement-breakpoint
CREATE INDEX "maint_warranty_document_idx" ON "maint_warranty" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "maint_warranty_deadline_idx" ON "maint_warranty" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "maint_work_supplier_party_idx" ON "maint_work" USING btree ("supplier_party_id");--> statement-breakpoint
CREATE INDEX "maint_work_deadline_idx" ON "maint_work" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "ins_claim_asset_idx" ON "ins_claim" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "ins_claim_adjuster_party_idx" ON "ins_claim" USING btree ("adjuster_party_id");--> statement-breakpoint
CREATE INDEX "ins_claim_matter_idx" ON "ins_claim" USING btree ("matter_id");--> statement-breakpoint
CREATE INDEX "ins_claim_entry_document_idx" ON "ins_claim_entry" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "ins_policy_insurer_party_idx" ON "ins_policy" USING btree ("insurer_party_id");--> statement-breakpoint
CREATE INDEX "ins_policy_agent_party_idx" ON "ins_policy" USING btree ("agent_party_id");--> statement-breakpoint
CREATE INDEX "ins_policy_document_idx" ON "ins_policy" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "ins_policy_deadline_idx" ON "ins_policy" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "ins_policy_asset_asset_idx" ON "ins_policy_asset" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "ins_premium_document_idx" ON "ins_premium" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "ins_premium_deadline_idx" ON "ins_premium" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "letting_manager_party_idx" ON "letting" USING btree ("manager_party_id");--> statement-breakpoint
CREATE INDEX "letting_contract_document_idx" ON "letting" USING btree ("contract_document_id");--> statement-breakpoint
CREATE INDEX "letting_deadline_idx" ON "letting" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "letting_party_party_idx" ON "letting_party" USING btree ("party_id");--> statement-breakpoint
CREATE INDEX "letting_rent_document_idx" ON "letting_rent" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "letting_rent_deadline_idx" ON "letting_rent" USING btree ("deadline_id");--> statement-breakpoint
CREATE INDEX "letting_report_document_idx" ON "letting_report" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "letting_report_deadline_idx" ON "letting_report" USING btree ("deadline_id");